
### Numpy Practice Questions

In [2]:
# 1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
import numpy as np
A = np.array([1,2,3,4,5,6,7,8,9,10])
B = np.array([7,8,9,10,11,12,13,14,15,16])
print(np.vstack((A,B)))
print(np.hstack((A,B)))

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 7  8  9 10 11 12 13 14 15 16]]
[ 1  2  3  4  5  6  7  8  9 10  7  8  9 10 11 12 13 14 15 16]


In [3]:
# 2. Find common elements between A and B. [Hint : Intersection of two sets]
print(np.intersect1d(A,B))

[ 7  8  9 10]


In [4]:
# 3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
print(A[np.where((A>=5)&(A<=10))])

[ 5  6  7  8  9 10]


In [5]:
# 4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(iris_2d[(iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0)])

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


### Practice Questions for Pandas

In [7]:
# 1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.iloc[::20,:3])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [9]:
#2. Replace missing values in Min.Price and Max.Price columns with their respective mean.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)
print(df)

   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31

In [12]:
# 3. How to get the rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
print(df)
print('Rows with sum greater than 100:')
print(df[df.sum(axis=1)>100])

     0   1   2   3
0   10  19  34  16
1   27  25  12  18
2   39  32  39  17
3   21  32  37  24
4   21  17  16  18
5   29  24  35  31
6   17  32  24  23
7   15  21  39  20
8   10  34  38  37
9   36  24  12  22
10  38  39  32  21
11  15  20  30  15
12  25  27  12  30
13  10  25  32  32
14  10  38  26  26
Rows with sum greater than 100:
     0   1   2   3
2   39  32  39  17
3   21  32  37  24
5   29  24  35  31
8   10  34  38  37
10  38  39  32  21
